version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform"
      - curl -O https://releases.hashicorp.com/terraform/1.0.5/terraform_1.0.5_linux_amd64.zip
      - unzip terraform_1.0.5_linux_amd64.zip
      - mv terraform /usr/local/bin/

  pre_build:
    commands:
      - echo "Initializing Terraform"
      - terraform init

  build:
    commands:
      - echo "Planning Terraform deployment"
      - terraform plan

  post_build:
    commands:
      - echo "Applying Terraform configuration"
      - terraform apply -auto-approve

artifacts:
  files:
    - '**/*'
